### ISSUE TITLE
Content filter is out of control

### ISSUE THREAD

**Issue by brodmo** [kronos-et-al/MensaApp#163]
The past few times I've tried to take a photo of a meal, I've been told that my image is too racy. Even with a dozen different angles, the same every time.
1. Take photo of meal -- the last two I've had an issue with are the red curry and the Leberkäse, but it happens for almost every meal.
2. See error, something about racy content, detected level 2, allowed level 1 (sorry, I didn't take a screenshot).

I would expect to be able to upload photos of meals, since that is part of the app's core functionality. I imagine that this bug it the reason why there are often no photos for meals.
I will provide screenshots the next time I encounter this issue.
I have an iPhone XR with iOS 17.5.1, the app version is 1.1.1.

**Comment by worldofjoni** [comment]
I have looked through the logs and seen a couple (242 since April 2024) of declined images that got rejected because of `adult`, `spoof`, or `racy` level 2, where we currently only allow level one. I now bumped all allowed levels to 2.

For comparison, in the same time period, 137 images got rejected because of a higher detected level.

The levels are those from [Google could vision safe search](https://cloud.google.com/vision/docs/detecting-safe-search), where the levels meaning can be seen [here](https://github.com/kronos-et-al/MensaApp/blob/3374dbd281d95b2cc63125ec508bfa8be3f75657/backend/src/layer/data/image_validation/image_evaluation.rs#L67).
